# Generated by Django 5.0.6 on 2024-06-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_favorito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorito',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='fecha_agregado',
        ),
    ]
